server:
  port: 9006
spring:
  application:
    name: workoverflow-complaint
  data:
    mongodb:
      host: 119.3.215.171
      database: complaintdb
  redis:
    host: 119.3.215.171
  rabbitmq:
    host: 119.3.215.171
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


eureka:
  client:
    service-url:
      defaultZone: http://119.3.215.171:6868/eureka
  instance:
    prefer-ip-address: true

