server:
  port: 9001
spring:
  application:
    name: workoverflow-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.215.171:3306/workoverflow_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 119.3.215.171
    
debug: false


eureka:
  client:
    service-url:
      defaultZone: http://119.3.215.171:6868/eureka
  instance:
    prefer-ip-address: true
