server:
  port: 9003
spring:
  application:
    name: workoverflow-qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.215.171:3306/workoverflow_qa?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 119.3.215.171

# jwt 配置
jwt:
  config:
    key: workoverflowisagoodwebforwebpeoplepleaseuseitthinkyou

eureka:
  client:
    service-url:
      defaultZone: http://119.3.215.171:6868/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
