server:
  port: 9011
spring:
  application:
    name: workoverflow-manager
  rabbitmq:
    host: 172.16.103.129
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://172.16.103.129:6868/eureka/
  # 跨域访问
  instance:
    prefer-ip-address: true
# jwt 配置
jwt:
  config:
    key: workoverflowisagoodwebforwebpeoplepleaseuseitthinkyou
    ttl: 3600000 #一个小时过期时间
# zuul网关配置
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
  prefix: /manager
  ignoredPatterns: /**/admin/login/**/, /**/sms/**/  # 忽略admin的登录路径
  routes:
    # 配置base路由
    workoverflow-base:
      path: /base/**  # 拦截所有为base开头的路径
      serviceId: workoverflow-base # 跳转到base服务
    workoverflow-article:
      path: /article/**
      serviceId: workoverflow-article
    workoverflow-friend:
      path: /friend/**
      serviceId: workoverflow-friend
    workoverflow-gathering:
      path: /activity/**
      serviceId: workoverflow-activity
    workoverflow-qa:
      path: /qa/**
      serviceId: workoverflow-qa
    workoverflow-recruit:
      path: /recruit/**
      serviceId: workoverflow-recruit
    workoverflow-search:
      path: /search/**
      serviceId: workoverflow-search
    workoverflow-complaint:
      path: /complaint/**
      serviceId: workoverflow-complaint
    workoverflow-user:
      path: /admin/**
      serviceId: workoverflow-user
