server:
  port: 9007
spring:
  application:
    name: workoverflow-search
  data:
    elasticsearch:
      cluster-nodes: 172.16.103.129:9300
  rabbitmq:
    host: 119.3.215.171
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://119.3.215.171:6868/eureka
  instance:
    prefer-ip-address: true
