server:
  port: 9001
spring:
  application:
    name: workoverflow-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.103.129:3306/workoverflow_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 172.16.103.129


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

